import type {
	IntrospectionApi,
	IntrospectionDocument,
	IntrospectionOperation,
	IntrospectionResponse,
	IntrospectionSchema,
} from "./introspection"
import type { WP_EndpointDefinition } from "./types"

const GENERATED_HEADER = `// Generated by Kizlo. Do not edit.\n`

function words(value: string): string[] {
	return value.split(/[^A-Za-z0-9]+/).filter(Boolean)
}

function pascal(value: string): string {
	const result = words(value)
		.map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
		.join("")
	return /^[0-9]/.test(result) ? `N${result}` : result || "Anonymous"
}

function camel(value: string): string {
	const result = pascal(value)
	return `${result[0]?.toLowerCase() ?? ""}${result.slice(1)}`
}

function schemaName(id: string): string {
	return `WP_${id.split(".").map(pascal).join("")}`
}

function endpointName(apiId: string, endpoint: string, suffix: string): string {
	return `WP_${apiId.split(".").map(pascal).join("")}${pascal(endpoint)}${suffix}`
}

function property(name: string): string {
	return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

function literal(value: unknown): string {
	if (value === undefined) return "undefined"
	if (value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
		return JSON.stringify(value)
	}
	return "unknown"
}

function jsdoc(description?: string, deprecated?: boolean, indent = ""): string {
	if (!description && !deprecated) return ""
	const lines = (description ?? "").replace(/\*\//g, "*\\/").split("\n")
	if (deprecated) lines.push("@deprecated")
	return `${indent}/**\n${lines.map((line) => `${indent} *${line ? ` ${line}` : ""}`).join("\n")}\n${indent} */\n`
}

interface RenderContext {
	names: Map<string, string>
	schemas: Map<string, IntrospectionSchema>
}

function sortedEntries<T>(value: Record<string, T>): Array<[string, T]> {
	return Object.entries(value).sort(([left], [right]) => left.localeCompare(right))
}

function withNullable(type: string, schema: IntrospectionSchema): string {
	return schema.nullable ? `${type} | null` : type
}

function inheritedPropertyTypes(
	schema: IntrospectionSchema,
	context: RenderContext,
	seen = new Set<string>(),
): { types: string[]; hasOptional: boolean } {
	const result = { types: [] as string[], hasOptional: false }
	const parents = schema.$extends ? (Array.isArray(schema.$extends) ? schema.$extends : [schema.$extends]) : []
	for (const parent of parents) {
		if (seen.has(parent)) continue
		seen.add(parent)
		const parentSchema = context.schemas.get(parent)
		if (!parentSchema) continue
		for (const child of Object.values(parentSchema.properties ?? {})) {
			result.types.push(renderType(child, context))
			result.hasOptional ||= !child.required
		}
		const inherited = inheritedPropertyTypes(parentSchema, context, seen)
		result.types.push(...inherited.types)
		result.hasOptional ||= inherited.hasOptional
	}
	return result
}

/**
 * An object with no properties, no patterns and no `additionalProperties`: one whose contents are
 * undescribed, not one required to be empty.
 *
 * `Record<string, never>` says the second, and it cannot be read from or written to, so a field like
 * the Store API's `additional_fields` came out unusable rather than merely unspecific. `unknown` is
 * what `additionalProperties: true` already renders to, and it is the same statement.
 */
const UNDESCRIBED_OBJECT = "Record<string, unknown>"

function renderObject(schema: IntrospectionSchema, context: RenderContext, indent = ""): string {
	const members: string[] = []
	const propertyTypes: string[] = []
	let hasOptionalProperty = false
	for (const [name, child] of sortedEntries(schema.properties ?? {})) {
		propertyTypes.push(renderType(child, context))
		hasOptionalProperty ||= !child.required
		members.push(
			`${jsdoc(child.description, child.deprecated, `${indent}\t`)}${indent}\t${property(name)}${child.required ? "" : "?"}: ${renderType(child, context)}`,
		)
	}

	const patterns = sortedEntries(schema.patternProperties ?? {}).map(([, child]) => renderType(child, context))
	if (schema.additionalProperties === true) patterns.push("unknown")
	else if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
		patterns.push(renderType(schema.additionalProperties, context))
	}
	if (patterns.length) {
		const inherited = inheritedPropertyTypes(schema, context)
		patterns.push(...propertyTypes)
		patterns.push(...inherited.types)
		if (hasOptionalProperty || inherited.hasOptional) patterns.push("undefined")
		members.push(`${indent}\t[key: string]: ${[...new Set(patterns)].join(" | ")}`)
	}

	if (!members.length) return UNDESCRIBED_OBJECT
	return `{\n${members.join("\n")}\n${indent}}`
}

function renderType(schema: IntrospectionSchema, context: RenderContext, indent = ""): string {
	let type: string
	if (schema.$ref) {
		type = context.names.get(schema.$ref) ?? schemaName(schema.$ref)
	} else if (schema.anyOf || schema.oneOf) {
		type = (schema.anyOf ?? schema.oneOf ?? []).map((child) => renderType(child, context, indent)).join(" | ")
	} else {
		switch (schema.type) {
			case "string":
			case "integer":
			case "number":
			case "boolean":
				if (schema.enum?.length) type = schema.enum.map(literal).join(" | ")
				else type = schema.type === "integer" || schema.type === "number" ? "number" : schema.type
				break
			case "file":
				type = "Blob"
				break
			case "array":
				type = `Array<${renderType(schema.items ?? {}, context, indent)}>`
				break
			default:
				type = renderObject(schema, context, indent)
				break
		}
	}

	const parents = schema.$extends ? (Array.isArray(schema.$extends) ? schema.$extends : [schema.$extends]) : []
	if (parents.length) {
		const inherited = parents.map((id) => context.names.get(id) ?? schemaName(id))
		const own = schema.type === "object" ? renderObject(schema, context, indent) : type
		type = [...inherited, ...(own === UNDESCRIBED_OBJECT ? [] : [own])].join(" & ")
	}

	return withNullable(type || "unknown", schema)
}

function renderNamedSchema(id: string, schema: IntrospectionSchema, context: RenderContext): string {
	const name = context.names.get(id) ?? schemaName(id)
	const parents = schema.$extends ? (Array.isArray(schema.$extends) ? schema.$extends : [schema.$extends]) : []
	const documentation = jsdoc(schema.description, schema.deprecated)
	if (schema.type === "object" && !schema.anyOf && !schema.oneOf && !schema.$ref) {
		if (schema.nullable) {
			const nonNullable = renderType({ ...schema, nullable: undefined }, context)
			return `${documentation}export type ${name} = (${nonNullable}) | null`
		}
		const inherited = parents.map((parent) => context.names.get(parent) ?? schemaName(parent))
		const extension = inherited.length ? ` extends ${inherited.join(", ")}` : ""
		const body = renderObject({ ...schema, nullable: undefined }, context)
		const declaration = body === UNDESCRIBED_OBJECT ? " {}" : ` ${body}`
		return `${documentation}export interface ${name}${extension}${declaration}`
	}
	return `${documentation}export type ${name} = ${renderType(schema, context)}`
}

function responseBody(response: IntrospectionResponse, context: RenderContext): string {
	if (!response.body) return "null"
	return renderType(response.body, context)
}

const NO_HEADERS = "Record<string, never>"

function responseHeaders(response: IntrospectionResponse, context: RenderContext): string {
	return response.headers ? renderType(response.headers, context) : NO_HEADERS
}

function responseStatus(status: string): string {
	return status === "default" ? "number" : status
}

function isSuccessStatus(status: string): boolean {
	return /^2\d\d$/.test(status)
}

/**
 * Every failing status of an endpoint carries the same error union, so spelling one member per
 * status would repeat it four or five times for no discrimination anyone can act on. They collapse
 * into a single `WP_Failure` over `number` — which also subsumes the status-0 transport failure.
 * Typed response headers are the one thing that does vary by status, so an endpoint that declares
 * them keeps a member per status.
 */
function renderResult(apiId: string, operationId: string, operation: IntrospectionOperation, context: RenderContext): string {
	const name = endpointName(apiId, operationId, "EndpointResult")
	const errors = operation.errors.map(literal).join(" | ") || "never"
	const responses = sortedEntries(operation.responses)
	const failures = responses.filter(([status]) => !isSuccessStatus(status))

	const variants = responses
		.filter(([status]) => isSuccessStatus(status))
		.map(([status, response]) => `WP_Success<${responseBody(response, context)}, ${status}, ${responseHeaders(response, context)}>`)

	const failureHeaders = new Set([NO_HEADERS, ...failures.map(([, response]) => responseHeaders(response, context))])
	if (failureHeaders.size === 1) {
		variants.push(`WP_Failure<${errors}, number, ${NO_HEADERS}>`)
	} else {
		for (const [status, response] of failures) {
			variants.push(`WP_Failure<${errors}, ${responseStatus(status)}, ${responseHeaders(response, context)}>`)
		}
		variants.push(`WP_TransportFailure<${errors}>`)
	}

	return `export type ${name} =\n\t| ${variants.join("\n\t| ")}`
}

/**
 * An operation that declares no parameters takes none, which is a stronger statement than the one
 * {@link UNDESCRIBED_OBJECT} makes and needs the type that refuses every key. The two look identical
 * in the document — `type: object` and nothing else — so only the position tells them apart: an
 * empty input is a complete description of an operation, where an empty field is a field nobody
 * described.
 */
const NO_INPUT = "Record<string, never>"

function renderInput(apiId: string, operationId: string, operation: IntrospectionOperation, context: RenderContext): string {
	const name = endpointName(apiId, operationId, "EndpointInput")
	const input = renderType(operation.input, context)
	const declaration = input === UNDESCRIBED_OBJECT ? NO_INPUT : input
	return `${jsdoc(operation.description ?? operation.summary, operation.deprecated)}export type ${name} = ${declaration}`
}

interface WordPressEndpointEntry {
	apiId: string
	namespace: string
	path: string
	operationId: string
	operation: IntrospectionOperation
}

interface WordPressEndpointNode {
	children: Map<string, WordPressEndpointNode>
	endpoints: WordPressEndpointEntry[]
}

function endpointTree(document: IntrospectionDocument): WordPressEndpointNode {
	const root: WordPressEndpointNode = { children: new Map(), endpoints: [] }
	for (const [apiId, api] of sortedEntries(document.apis)) {
		let node = root
		for (const segment of apiId.split(".")) {
			const key = camel(segment)
			let child = node.children.get(key)
			if (!child) {
				child = { children: new Map(), endpoints: [] }
				node.children.set(key, child)
			}
			node = child
		}
		for (const [path, operations] of sortedEntries(api.paths)) {
			for (const [operationId, operation] of sortedEntries(operations)) {
				node.endpoints.push({ apiId, namespace: api.namespace, path, operationId, operation })
			}
		}
	}
	return root
}

function sortedChildren(node: WordPressEndpointNode): Array<[string, WordPressEndpointNode]> {
	return [...node.children.entries()].sort(([left], [right]) => left.localeCompare(right))
}

function sortedEndpoints(node: WordPressEndpointNode): WordPressEndpointEntry[] {
	return [...node.endpoints].sort((left, right) => left.operationId.localeCompare(right.operationId))
}

function endpointDefinition(entry: WordPressEndpointEntry): WP_EndpointDefinition {
	const pathParameters = sortedEntries(entry.operation.input.properties ?? {})
		.filter(([, schema]) => schema.in === "path")
		.map(([name]) => name)
	const responseContentTypes = Object.fromEntries(
		sortedEntries(entry.operation.responses).map(([status, response]) => [status, response.content_type]),
	)
	return {
		namespace: entry.namespace,
		path: entry.path,
		method: entry.operation.method,
		pathParameters,
		...(entry.operation.input.content_type ? { requestContentType: entry.operation.input.content_type } : {}),
		responseContentTypes,
	}
}

function renderRecord(value: Record<string, string | undefined>): string {
	const entries = sortedEntries(value)
		.filter(([, item]) => item !== undefined)
		.map(([key, item]) => `${property(key)}: ${literal(item)}`)
	return `{ ${entries.join(", ")} }`
}

/** One endpoint's definition, inlined at its call site in the generated tree. */
function renderDefinition(definition: WP_EndpointDefinition): string {
	const members = [
		`namespace: ${literal(definition.namespace)}`,
		`path: ${literal(definition.path)}`,
		`method: ${literal(definition.method)}`,
		`pathParameters: [${definition.pathParameters.map(literal).join(", ")}]`,
		...(definition.requestContentType ? [`requestContentType: ${literal(definition.requestContentType)}`] : []),
		`responseContentTypes: ${renderRecord(definition.responseContentTypes)}`,
	]
	return `{ ${members.join(", ")} }`
}

/**
 * The endpoint tree as data: every leaf spells its own input and result types and is its own
 * definition, but binds nothing. Kizlo pairs the tree with a transport at runtime, so the generated
 * module never names a connection and a package that only wants the types still gets the whole shape.
 */
function renderEndpointNode(node: WordPressEndpointNode, indent: string): string {
	const entries: string[] = []
	for (const [key, child] of sortedChildren(node)) {
		entries.push(`${indent}${property(key)}: ${renderEndpointNode(child, `${indent}\t`)},`)
	}
	for (const entry of sortedEndpoints(node)) {
		const input = endpointName(entry.apiId, entry.operationId, "EndpointInput")
		const result = endpointName(entry.apiId, entry.operationId, "EndpointResult")
		const documentation = jsdoc(entry.operation.description ?? entry.operation.summary, entry.operation.deprecated, indent)
		const definition = renderDefinition(endpointDefinition(entry))
		entries.push(`${documentation}${indent}${property(entry.operationId)}: wpEndpoint<${input}, ${result}>(${definition}),`)
	}
	if (entries.length === 0) return "{}"
	return `{\n${entries.join("\n")}\n${indent.slice(0, -1)}}`
}

function operationEntries(apiId: string, api: IntrospectionApi): Array<[string, IntrospectionOperation]> {
	const entries: Array<[string, IntrospectionOperation]> = []
	for (const [, operations] of sortedEntries(api.paths)) {
		for (const [operationId, operation] of sortedEntries(operations)) entries.push([operationId, operation])
	}
	return entries
}

/**
 * Transport members the client falls through to for anything the tree does not define. A namespace
 * named after one would shadow it, so this fails at generation rather than at the call that misses.
 */
const TRANSPORT_MEMBERS = ["delete", "get", "patch", "post", "put", "request", "resolveList", "resolveListMetadata"]

function assertUniqueGeneratedNames(document: IntrospectionDocument): void {
	for (const apiId of Object.keys(document.apis)) {
		const namespace = camel(apiId.split(".")[0] ?? apiId)
		if (TRANSPORT_MEMBERS.includes(namespace)) {
			throw new Error(`Cannot generate api ${apiId}: namespace ${namespace} would shadow the transport method of the same name.`)
		}
	}

	const names = new Map<string, string>()
	const add = (name: string, source: string) => {
		const previous = names.get(name)
		if (previous && previous !== source) {
			throw new Error(`Cannot generate ${source}: TypeScript name ${name} is also produced by ${previous}.`)
		}
		names.set(name, source)
	}
	for (const id of Object.keys(document.schemas)) add(schemaName(id), `schema ${id}`)
	for (const [apiId, api] of sortedEntries(document.apis)) {
		for (const [operationId] of operationEntries(apiId, api)) {
			add(endpointName(apiId, operationId, "EndpointInput"), `endpoint ${apiId}.${operationId} input`)
			add(endpointName(apiId, operationId, "EndpointResult"), `endpoint ${apiId}.${operationId} result`)
		}
	}
}

const RUNTIME_TYPES = ["WP_Failure", "WP_Success", "WP_TransportFailure"]

const REGISTRY = `declare module "kizlo" {\n\tinterface WordPressClientRegistry {\n\t\tendpoints: typeof endpoints\n\t}\n}`

/**
 * The `kizlo` names a generated module uses: whatever its bodies mention, plus the two the tree
 * itself always needs. `wpEndpoint` is the only value among them, so the rest erase at build.
 */
function kizloImports(body: string): string {
	const types = new Set(["WP_Client", ...RUNTIME_TYPES.filter((name) => new RegExp(`\\b${name}\\b`).test(body))])
	return [...types, "wpEndpoint"]
		.sort()
		.map((name) => (types.has(name) ? `type ${name}` : name))
		.join(", ")
}

function generatedModule(hash: string, imports: string, body: string): string {
	return `${GENERATED_HEADER}// Introspection ${hash}\n\n${imports}\n\n${body}\n`
}

export function generateWordPressClient(document: IntrospectionDocument): string {
	assertUniqueGeneratedNames(document)
	const names = new Map(Object.keys(document.schemas).map((id) => [id, schemaName(id)]))
	const context = { names, schemas: new Map(Object.entries(document.schemas)) }
	const declarations = sortedEntries(document.schemas).map(([id, schema]) => renderNamedSchema(id, schema, context))
	for (const [apiId, api] of sortedEntries(document.apis)) {
		for (const [operationId, operation] of operationEntries(apiId, api)) {
			declarations.push(renderInput(apiId, operationId, operation, context))
			declarations.push(renderResult(apiId, operationId, operation, context))
		}
	}

	const tree = endpointTree(document)
	const body = declarations.join("\n\n")

	const moduleBody = [
		body,
		`export const endpoints = ${renderEndpointNode(tree, "\t")}`,
		`export type WordPressClient = WP_Client<typeof endpoints>`,
		REGISTRY,
	].join("\n\n")

	return generatedModule(document.hash, `import { ${kizloImports(body)} } from "kizlo"`, moduleBody)
}
