packages:
  - web
  - playground
  - packages/*
  - tooling/*
  - plugins/*

catalog:
  next: ^16.2.9
  jose: 6.1.0
  zod: ^4.3.6
  tsdown: ^0.15.6
  vitest: ^3.2.4
  typescript: ^5.9.3
  '@types/node': ^22.18.12
  '@oslojs/crypto': ^1.0.1

catalogs:
  react19:
    react: ^19.2.3
    react-dom: ^19.2.3
    '@types/react': ^19.2.3
    '@types/react-dom': ^19.2.3

onlyBuiltDependencies:
  - esbuild
  - sharp
  - "@parcel/watcher"
  - core-js
  - core-js-pure
  - unrs-resolver
