import fs from "node:fs"
import path from "node:path"
import { resolveWordPressConnection } from "../../kizlo"
import { generateContract } from "../../shared/contract"
import type { AnyProcedureRouter } from "../../shared/procedure"
import { fetchIntrospection } from "../../wordpress/fetch-introspection"
import { generateWordPressClient } from "../../wordpress/generate"
import type { IntrospectionDiagnostic, IntrospectionDocument } from "../../wordpress/introspection"
import type { WordPressCredentials } from "../../wordpress/types"
import { loadEnvFiles } from "../utils"
import { WORDPRESS_CLIENT_META_REL } from "../wp/constants"
import type { ResolvedConfig } from "./config"
import { importIgnoringVirtualModules } from "./jiti"
import { log } from "./logger"

/**
 * The generated barrel — also written as a stub by `kizlo init`. It re-exports `endpoints` rather
 * than pre-wrapping it: a server entry passes `wordpress: { endpoints }` itself, so the rest of the
 * WordPress options stay visible at the call site instead of hiding inside a generated object.
 */
export const CONTRACT_BARREL = [
	`import type { router } from ".."`,
	`import contractJson from "./contract.json"`,
	``,
	`export const contract = contractJson as unknown as typeof router`,
	`export { endpoints, type WordPressClient } from "./wordpress"`,
	``,
].join("\n")

/**
 * `wordpress.ts` before the first generation. WordPress is reachable but untyped until then, so a
 * freshly scaffolded project compiles — including kizlo's own procedures — before it has ever
 * connected. `kizlo dev` / `kizlo generate` replaces this with the real client. `any` rather than an
 * empty tree on purpose: every endpoint a procedure names has to resolve to something until the
 * real shapes arrive, which `WP_Client` preserves by passing `any` through.
 */
export const WORDPRESS_STUB = [
	// The import is load-bearing: without one, `declare module "kizlo"` has no module to augment.
	`import type { WP_Client } from "kizlo"`,
	``,
	`export const endpoints = {} as any`,
	``,
	`export type WordPressClient = WP_Client<typeof endpoints>`,
	``,
	`declare module "kizlo" {`,
	`\tinterface WordPressClientRegistry {`,
	`\t\tendpoints: typeof endpoints`,
	`\t}`,
	`}`,
	``,
].join("\n")

/** Write atomically: a reader never observes a half-written file. */
let atomicWriteSequence = 0

function atomicWrite(file: string, data: string): void {
	const tmp = `${file}.${process.pid}.${atomicWriteSequence++}.tmp`
	try {
		fs.writeFileSync(tmp, data)
		fs.renameSync(tmp, file)
	} finally {
		if (fs.existsSync(tmp)) fs.unlinkSync(tmp)
	}
}

interface WordPressMeta {
	etag: string
	hash: string
}

/** Enough of a generated file to hold its header: `// Generated by Kizlo` then `// Introspection <hash>`. */
const INTROSPECTION_STAMP_BYTES = 256

/** The introspection hash a generated file was written from, read without loading the whole file. */
function introspectionStamp(file: string): string | undefined {
	let handle: number | undefined
	try {
		handle = fs.openSync(file, "r")
		const buffer = Buffer.alloc(INTROSPECTION_STAMP_BYTES)
		const bytes = fs.readSync(handle, buffer, 0, buffer.length, 0)
		return /^\/\/ Introspection (\S+)$/m.exec(buffer.toString("utf8", 0, bytes))?.[1]
	} catch {
		return undefined
	} finally {
		if (handle !== undefined) fs.closeSync(handle)
	}
}

/**
 * The ETag to revalidate with, or undefined to fetch afresh. An ETag is only worth sending when the
 * file it describes is still on disk and was written from the same introspection document it
 * names: a stub, a hand-edit, or output from an older generator all have to be replaced, and
 * answering 304 to any of them would leave the project compiling against something WordPress never served.
 */
function readWordPressMeta(metaPath: string, generatedFile: string): WordPressMeta | undefined {
	try {
		const value = JSON.parse(fs.readFileSync(metaPath, "utf8")) as Partial<WordPressMeta>
		if (typeof value.etag !== "string" || typeof value.hash !== "string") return undefined
		if (introspectionStamp(generatedFile) !== value.hash) return undefined
		return value as WordPressMeta
	} catch {
		return undefined
	}
}

/** The fetch cache a generated file revalidates against, keyed to the document it was written from. */
function wordPressMeta(etag: string | undefined, hash: string): string {
	return `${JSON.stringify({ etag, hash }, null, "\t")}\n`
}

/** Where a diagnostic landed: `schema_id > api_id > path > operation > pointer > keyword`, as sent. */
function diagnosticLocation(diagnostic: IntrospectionDiagnostic): string {
	return Object.values(diagnostic.data).filter(Boolean).join(" > ")
}

function formatDiagnostic(diagnostic: IntrospectionDiagnostic): string {
	const location = diagnosticLocation(diagnostic)
	return `${diagnostic.type}: ${location ? `${location}: ` : ""}${diagnostic.message}`
}

/**
 * WordPress publishes everything that survived validation and names what it had to drop, so what a
 * partial contract is worth is the generator's call rather than the transport's. Taking it is the
 * default: a third-party plugin's broken declaration then costs its own routes and nothing else,
 * where refusing the document costs the project every route that still works, for a mistake in code
 * it does not own. Strict generation makes the opposite trade for CI, where a client silently short
 * of routes typechecks clean and ships the gap.
 */
export class PartialContractError extends Error {
	readonly excluded: number

	constructor(excluded: number) {
		super(`WordPress excluded ${excluded} ${excluded === 1 ? "contribution" : "contributions"} from the contract.`)
		this.name = "PartialContractError"
		this.excluded = excluded
	}
}

export interface GenerateWordPressOptions {
	credentials?: WordPressCredentials
	fetch?: typeof globalThis.fetch
	/** Refuse a document WordPress had to exclude anything from, leaving the client on disk untouched. */
	strict?: boolean
}

/**
 * Say what the document says about itself, then apply the policy. Warnings mean a declaration lost a
 * constraint and still types correctly, so they never gate anything; errors mean a contribution was
 * dropped and its routes and types are absent from what follows.
 */
function reportDiagnostics(document: IntrospectionDocument, strict: boolean): void {
	for (const diagnostic of document.diagnostics) {
		if (diagnostic.type === "warning") log.warn(formatDiagnostic(diagnostic))
		else log.error(formatDiagnostic(diagnostic))
	}

	const excluded = new Set(document.diagnostics.filter((diagnostic) => diagnostic.type === "error").map(diagnosticLocation))
	if (!excluded.size) return
	if (strict) throw new PartialContractError(excluded.size)
	log.warn(
		`Generating without the ${excluded.size} excluded ${excluded.size === 1 ? "contribution" : "contributions"} above. ` +
			"Their routes and types are missing from the client; `kizlo generate --strict` refuses the contract instead.",
	)
}

/** Fetch `/introspect`, reporting its diagnostics in the CLI's voice. Returns undefined on a 304. */
async function fetchDocument(
	cwd: string,
	options: GenerateWordPressOptions,
	etag?: string,
): Promise<Awaited<ReturnType<typeof fetchIntrospection>> | undefined> {
	loadEnvFiles(cwd)
	const credentials = options.credentials ?? resolveWordPressConnection(undefined).credentials
	// Strict generation never revalidates: a 304 carries no diagnostics, so a warm meta file left over
	// from a partial generation would answer "unchanged" and pass a run whose whole job is to fail.
	const result = await fetchIntrospection(credentials, { etag: options.strict ? undefined : etag, fetch: options.fetch })

	if (result.status === "not-modified") return undefined
	if (!result.document) throw new Error("WordPress introspection returned no document.")
	reportDiagnostics(result.document, options.strict === true)
	return result
}

export async function generateWordPressOnce(
	cfg: ResolvedConfig,
	options: GenerateWordPressOptions = {},
): Promise<"generated" | "unchanged"> {
	const metaPath = path.resolve(cfg.cwd, cfg.wordpressMetaPath)
	const etag = readWordPressMeta(metaPath, path.resolve(cfg.cwd, cfg.wordpressPath))?.etag
	const result = await fetchDocument(cfg.cwd, options, etag)
	if (!result?.document) return "unchanged"

	writeGeneratedWordPress(cfg, generateWordPressClient(result.document), wordPressMeta(result.etag, result.document.hash))
	return "generated"
}

/**
 * Write `<dir>/wordpress.ts` once for a whole workspace. Every package that ships procedures compiles
 * against the same file, so there is one description of WordPress in the repo rather than one per
 * package drifting apart. One shape too: a package that only wants the types today still gets the
 * class, so reaching for the runtime later needs no regeneration.
 */
export async function generateWorkspaceClientOnce(
	cwd: string,
	dir: string,
	options: GenerateWordPressOptions = {},
): Promise<"generated" | "unchanged"> {
	const file = path.resolve(cwd, dir, "wordpress.ts")
	// Its own cache file, not the app's: a project setting both would otherwise have two generated
	// files revalidating against one ETag, and the loser would refetch the whole document every poll.
	const metaPath = path.resolve(cwd, WORDPRESS_CLIENT_META_REL)
	const result = await fetchDocument(cwd, options, readWordPressMeta(metaPath, file)?.etag)
	if (!result?.document) return "unchanged"

	const contents = generateWordPressClient(result.document)
	fs.mkdirSync(path.dirname(metaPath), { recursive: true })
	atomicWrite(metaPath, wordPressMeta(result.etag, result.document.hash))
	if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === contents) return "unchanged"

	fs.mkdirSync(path.dirname(file), { recursive: true })
	atomicWrite(file, contents)
	return "generated"
}

function writeGeneratedWordPress(cfg: ResolvedConfig, client: string, meta: string): void {
	const metaPath = path.resolve(cfg.cwd, cfg.wordpressMetaPath)
	fs.mkdirSync(path.resolve(cfg.cwd, cfg.generatedDir), { recursive: true })
	fs.mkdirSync(path.dirname(metaPath), { recursive: true })
	atomicWrite(path.resolve(cfg.cwd, cfg.wordpressPath), client)
	atomicWrite(metaPath, meta)
}

/**
 * Loads the Kizlo server, builds its contract, and writes `contract.json` and
 * the generated barrel. Returns false when the entry has no Kizlo server.
 */
export async function generateOnce(cfg: ResolvedConfig, options: GenerateWordPressOptions = {}): Promise<boolean> {
	loadEnvFiles(cfg.cwd)
	const entry = path.resolve(cfg.cwd, cfg.serverEntry)
	const { router } = await importIgnoringVirtualModules<{ router?: AnyProcedureRouter }>(cfg.cwd, entry)

	if (!router) return false

	const contract = JSON.stringify(await generateContract(router))
	const wordpress = await generateWordPressOnce(cfg, options)

	fs.mkdirSync(path.resolve(cfg.cwd, cfg.generatedDir), { recursive: true })
	atomicWrite(path.resolve(cfg.cwd, cfg.contractPath), contract)
	atomicWrite(path.resolve(cfg.cwd, cfg.barrelPath), CONTRACT_BARREL)

	if (wordpress === "generated") log.success("WordPress client generated")
	return true
}
