import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { afterEach, describe, expect, test, vi } from "vitest"
import { INTROSPECTION_FIXTURE } from "../../wordpress/introspection.fixture"
import type { ResolvedConfig } from "./config"
import { generateWordPressOnce } from "./generate"

function config(cwd: string): ResolvedConfig {
	return {
		cwd,
		dir: "src/kizlo",
		serverDir: "src/kizlo/server",
		serverEntry: "src/kizlo/server/index.ts",
		generatedDir: "src/kizlo/server/generated",
		contractPath: "src/kizlo/server/generated/contract.json",
		barrelPath: "src/kizlo/server/generated/index.ts",
		wordpressPath: "src/kizlo/server/generated/wordpress.ts",
		wordpressMetaPath: ".kizlo/wordpress.meta.json",
	}
}

function modified(document = INTROSPECTION_FIXTURE, etag = '"fixture"'): Response {
	return Response.json(document, { headers: { etag } })
}

function seedEnv(cwd: string): void {
	fs.writeFileSync(path.join(cwd, ".env"), "KIZLO_WP_URL=https://wp.example\nKIZLO_WP_USERNAME=admin\nKIZLO_WP_APP_PASSWORD=secret\n")
}

afterEach(() => {
	for (const key of ["KIZLO_WP_URL", "KIZLO_WP_USERNAME", "KIZLO_WP_APP_PASSWORD"]) delete process.env[key]
})

describe("generateWordPressOnce", () => {
	test("fetches once, writes current output, and reuses the ETag without rewriting", async () => {
		const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "kizlo-generate-"))
		seedEnv(cwd)
		const cfg = config(cwd)
		const fetch = vi
			.fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>()
			.mockResolvedValueOnce(modified())
			.mockResolvedValueOnce(new Response(null, { status: 304 }))

		expect(await generateWordPressOnce(cfg, { fetch: fetch as unknown as typeof globalThis.fetch })).toBe("generated")
		const source = path.join(cwd, cfg.wordpressPath)
		const first = fs.readFileSync(source, "utf8")
		const mtime = fs.statSync(source).mtimeMs

		expect(await generateWordPressOnce(cfg, { fetch: fetch as unknown as typeof globalThis.fetch })).toBe("unchanged")
		expect(fs.readFileSync(source, "utf8")).toBe(first)
		expect(fs.statSync(source).mtimeMs).toBe(mtime)
		expect(new Headers(fetch.mock.calls[1]?.[1]?.headers).get("If-None-Match")).toBe('"fixture"')
		expect(fetch).toHaveBeenCalledTimes(2)
	})

	test.each([
		["a stub", "export {}\n"],
		["output from an older generator", "// Generated by Kizlo. Do not edit.\n// Introspection sha256:stale\n"],
	])("refetches instead of revalidating when the contract on disk is %s", async (_label, contents) => {
		const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "kizlo-generate-"))
		seedEnv(cwd)
		const cfg = config(cwd)
		const fetch = vi.fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>(async () => modified())

		await generateWordPressOnce(cfg, { fetch: fetch as unknown as typeof globalThis.fetch })
		const file = path.join(cwd, cfg.wordpressPath)
		const generated = fs.readFileSync(file, "utf8")
		fs.writeFileSync(file, contents)

		// The ETag still matches, but the file it describes no longer does, so it must not be sent.
		expect(await generateWordPressOnce(cfg, { fetch: fetch as unknown as typeof globalThis.fetch })).toBe("generated")
		expect(new Headers(fetch.mock.calls[1]?.[1]?.headers).get("If-None-Match")).toBeNull()
		expect(fs.readFileSync(file, "utf8")).toBe(generated)
	})

	test("changes generated output when the selected contract changes", async () => {
		const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "kizlo-generate-"))
		seedEnv(cwd)
		const cfg = config(cwd)
		const fetch = vi
			.fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>()
			.mockResolvedValueOnce(modified())
			.mockResolvedValueOnce(
				modified(
					{
						...INTROSPECTION_FIXTURE,
						hash: `sha256:${"b".repeat(64)}`,
						schemas: { ...INTROSPECTION_FIXTURE.schemas, "acme.album": { type: "object", properties: {} } },
					},
					'"changed"',
				),
			)

		await generateWordPressOnce(cfg, { fetch: fetch as unknown as typeof globalThis.fetch })
		const before = fs.readFileSync(path.join(cwd, cfg.wordpressPath), "utf8")
		await generateWordPressOnce(cfg, { fetch: fetch as unknown as typeof globalThis.fetch })
		const after = fs.readFileSync(path.join(cwd, cfg.wordpressPath), "utf8")
		expect(after).not.toBe(before)
		expect(after).toContain("WP_AcmeAlbum")
	})

	test.each([
		["fetch failure", () => Promise.reject(new Error("offline"))],
		["invalid document", () => Promise.resolve(Response.json({ nope: true }))],
		[
			"error diagnostic",
			() =>
				Promise.resolve(
					modified({
						...INTROSPECTION_FIXTURE,
						diagnostics: [{ type: "error", message: "Excluded operation.", data: { api_id: "acme.broken" } }],
					}),
				),
		],
	])("preserves the last valid output after a %s", async (_label, next) => {
		const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "kizlo-generate-"))
		seedEnv(cwd)
		const cfg = config(cwd)
		await generateWordPressOnce(cfg, { fetch: vi.fn(async () => modified()) as unknown as typeof globalThis.fetch })
		const sourcePath = path.join(cwd, cfg.wordpressPath)
		const metaPath = path.join(cwd, cfg.wordpressMetaPath)
		const source = fs.readFileSync(sourcePath, "utf8")
		const meta = fs.readFileSync(metaPath, "utf8")

		await expect(generateWordPressOnce(cfg, { fetch: vi.fn(next) as unknown as typeof globalThis.fetch })).rejects.toThrow()
		expect(fs.readFileSync(sourcePath, "utf8")).toBe(source)
		expect(fs.readFileSync(metaPath, "utf8")).toBe(meta)
	})
})
