import fs from "node:fs"
import path from "node:path"
import { isPluginVersionSupported, pluginUpdateMessage } from "@kizlo/shared"
import { node } from "../../integrations/node/integration"
import { integrationEnv, resolveWordPressConnection } from "../../kizlo"
import { generateContract } from "../../shared/contract"
import type { AnyProcedureTree } from "../../shared/procedure"
import { fetchIntrospection } from "../../wordpress/fetch-introspection"
import { generateWordPressModule } from "../../wordpress/generate"
import { type IntrospectionDiagnostic, type IntrospectionDocument, IntrospectionVersionError } from "../../wordpress/introspection"
import { assertGeneratedClientCompiles, GeneratedClientTypeError } from "../../wordpress/typecheck"
import type { WordPressCredentials } from "../../wordpress/types"
import { loadEnvFiles } from "../utils"
import type { ResolvedConfig } from "./config"
import { importIgnoringVirtualModules } from "./jiti"
import { log } from "./logger"

/**
 * The generated barrel is also written as a stub by `kizlo init`. It re-exports `endpoints` rather
 * than pre-wrapping it: a server entry passes `wordpress: { endpoints }` itself, so the rest of the
 * WordPress options stay visible at the call site instead of hiding inside a generated object.
 */
export const CONTRACT_BARREL = [
	`import type { procedures } from ".."`,
	`import contractJson from "./contract.json"`,
	``,
	`export const contract = contractJson as unknown as typeof procedures`,
	`export { endpoints, type WordPressClient } from "./introspection"`,
	``,
].join("\n")

export class LegacyRouterExportError extends Error {
	readonly name = "LegacyRouterExportError"

	constructor(entry: string) {
		super(
			`The Kizlo server at ${entry} exports \`router\`, which is no longer supported. Rename that export to \`procedures\` and run \`kizlo generate\` again.`,
		)
	}
}

/**
 * `introspection.ts` before the first generation. WordPress is reachable but untyped until then, so a
 * freshly scaffolded project compiles, including Kizlo's own procedures, before it has ever
 * connected. `kizlo dev` / `kizlo generate` replaces this with the real introspection. `any` rather than
 * an empty tree on purpose: every endpoint a procedure names has to resolve to something until the
 * real shapes arrive, which `WP_Client` preserves by passing `any` through.
 */
export const INTROSPECTION_STUB = [
	// The import is load-bearing: without one, `declare module "kizlo"` has no module to augment.
	`import type { WP_Client } from "kizlo"`,
	``,
	`export const endpoints = {} as any`,
	``,
	`export type WordPressClient = WP_Client<typeof endpoints>`,
	``,
	`declare module "kizlo" {`,
	`\tinterface WordPressClientRegistry {`,
	`\t\tendpoints: typeof endpoints`,
	`\t}`,
	`\tinterface WordPressEndpointRegistry {`,
	`\t\t[path: string]: any`,
	`\t}`,
	`\tinterface WordPressCustomFieldsRegistry {`,
	`\t\t[path: string]: Record<string, unknown>`,
	`\t}`,
	`}`,
	``,
].join("\n")

/** Write atomically: a reader never observes a half-written file. */
let atomicWriteSequence = 0

function atomicWrite(file: string, data: string): void {
	const tmp = `${file}.${process.pid}.${atomicWriteSequence++}.tmp`
	try {
		fs.writeFileSync(tmp, data)
		fs.renameSync(tmp, file)
	} finally {
		if (fs.existsSync(tmp)) fs.unlinkSync(tmp)
	}
}

interface WordPressMeta {
	etag: string
	hash: string
}

/** Enough of a generated file to hold its header: `// Generated by Kizlo` then `// Introspection <hash>`. */
const INTROSPECTION_STAMP_BYTES = 256

/** The introspection hash a generated file was written from, read without loading the whole file. */
function introspectionStamp(file: string): string | undefined {
	let handle: number | undefined
	try {
		handle = fs.openSync(file, "r")
		const buffer = Buffer.alloc(INTROSPECTION_STAMP_BYTES)
		const bytes = fs.readSync(handle, buffer, 0, buffer.length, 0)
		return /^\/\/ Introspection (\S+)$/m.exec(buffer.toString("utf8", 0, bytes))?.[1]
	} catch {
		return undefined
	} finally {
		if (handle !== undefined) fs.closeSync(handle)
	}
}

/**
 * The ETag to revalidate with, or undefined to fetch afresh. An ETag is only worth sending when the
 * file it describes is still on disk and was written from the same introspection document it
 * names: a stub, a hand-edit, or output from an older generator all have to be replaced, and
 * answering 304 to any of them would leave the project compiling against something WordPress never served.
 */
function readWordPressMeta(metaPath: string, generatedFile: string): WordPressMeta | undefined {
	try {
		const value = JSON.parse(fs.readFileSync(metaPath, "utf8")) as Partial<WordPressMeta>
		if (typeof value.etag !== "string" || typeof value.hash !== "string") return undefined
		if (introspectionStamp(generatedFile) !== value.hash) return undefined
		return value as WordPressMeta
	} catch {
		return undefined
	}
}

/** The fetch cache a generated file revalidates against, keyed to the document it was written from. */
function wordPressMeta(etag: string | undefined, hash: string): string {
	return `${JSON.stringify({ etag, hash }, null, "\t")}\n`
}

/** Where a diagnostic landed: `schema_id > api_id > path > operation > pointer > keyword`, as sent. */
function diagnosticLocation(diagnostic: IntrospectionDiagnostic): string {
	return Object.values(diagnostic.data).filter(Boolean).join(" > ")
}

function formatDiagnostic(diagnostic: IntrospectionDiagnostic): string {
	const location = diagnosticLocation(diagnostic)
	return `${diagnostic.type}: ${location ? `${location}: ` : ""}${diagnostic.message}`
}

/**
 * WordPress publishes everything that survived validation and names what it had to drop, so what a
 * partial contract is worth is the generator's call rather than the transport's. Taking it is the
 * default: a third-party plugin's broken declaration then costs its own routes and nothing else,
 * where refusing the document costs the project every route that still works, for a mistake in code
 * it does not own. Strict generation makes the opposite trade for CI, where an introspection silently
 * short of routes typechecks clean and ships the gap.
 */
export class PartialContractError extends Error {
	readonly excluded: number

	constructor(excluded: number) {
		super(`WordPress excluded ${excluded} ${excluded === 1 ? "contribution" : "contributions"} from the contract.`)
		this.name = "PartialContractError"
		this.excluded = excluded
	}
}

/**
 * Report a failed generation under `message`. A version mismatch and a refused partial contract are
 * diagnoses rather than faults: the message is the whole report, and the stack consola would print
 * beneath it buries the one line the user has to act on. Anything else is a fault and keeps its stack.
 */
export function reportGenerationError(message: string, error: unknown): void {
	if (error instanceof IntrospectionVersionError || error instanceof PartialContractError) log.error(error.message)
	else if (error instanceof GeneratedClientTypeError) log.error(error.message)
	else log.error(message, error)
}

export interface GenerateWordPressOptions {
	credentials?: WordPressCredentials
	fetch?: typeof globalThis.fetch
	/** Refuse a document WordPress had to exclude anything from, leaving the introspection on disk untouched. */
	strict?: boolean
}

/**
 * Say what the document says about itself, then apply the policy. Warnings mean a declaration lost a
 * constraint and still types correctly, so they never gate anything; errors mean a contribution was
 * dropped and its routes and types are absent from what follows.
 */
function reportDiagnostics(document: IntrospectionDocument, strict: boolean): void {
	for (const diagnostic of document.diagnostics) {
		if (diagnostic.type === "warning") log.warn(formatDiagnostic(diagnostic))
		else log.error(formatDiagnostic(diagnostic))
	}

	const excluded = new Set(document.diagnostics.filter((diagnostic) => diagnostic.type === "error").map(diagnosticLocation))
	if (!excluded.size) return
	if (strict) throw new PartialContractError(excluded.size)
	log.warn(
		`Generating without the ${excluded.size} excluded ${excluded.size === 1 ? "contribution" : "contributions"} above. ` +
			"Their routes and types are missing from the introspection; `kizlo generate --strict` refuses the contract instead.",
	)
}

/**
 * Plugin versions already named as outdated. `kizlo dev` refetches every few seconds, and the answer
 * cannot change until the plugin does, so the warning is worth one line per version rather than one
 * per poll. An updated plugin that is still too old is a version this has not seen, and says so again.
 */
const reportedPluginVersions = new Set<string>()

/**
 * Name a plugin too old for this package at generation, where it is still actionable, rather than
 * leaving it to the runtime's first request. A warning either way, strict included: strict decides
 * what to do about routes WordPress excluded, and an outdated plugin excludes nothing by itself.
 */
function reportPluginVersion(installed: string | null): void {
	if (isPluginVersionSupported(installed)) return
	const key = installed ?? ""
	if (reportedPluginVersions.has(key)) return
	reportedPluginVersions.add(key)
	log.warn(pluginUpdateMessage(installed))
}

/** Fetch `/introspect`, reporting its diagnostics in the CLI's voice. Returns undefined on a 304. */
async function fetchDocument(
	cwd: string,
	options: GenerateWordPressOptions,
	etag?: string,
): Promise<Awaited<ReturnType<typeof fetchIntrospection>> | undefined> {
	loadEnvFiles(cwd)
	const credentials = options.credentials ?? resolveWordPressConnection(undefined, integrationEnv([node()])).credentials
	// Strict generation never revalidates: a 304 carries no diagnostics, so a warm meta file left over
	// from a partial generation would answer "unchanged" and pass a run whose whole job is to fail.
	const result = await fetchIntrospection(credentials, { etag: options.strict ? undefined : etag, fetch: options.fetch })
	// Before the 304, which carries the header too: a project generating nothing new still has a plugin
	// its introspection may have outgrown.
	reportPluginVersion(result.pluginVersion)

	if (result.status === "not-modified") return undefined
	if (!result.document) throw new Error("WordPress introspection returned no document.")
	reportDiagnostics(result.document, options.strict === true)
	return result
}

/**
 * Produce the introspection source without writing it or its ETag cache. Health checks use this to ask
 * the same generator as `kizlo generate` what should be on disk, while leaving a contributor's
 * checkout untouched. Callers choose strictness just as generation does.
 */
export async function generateIntrospectionSource(cwd: string, options: GenerateWordPressOptions = {}): Promise<string> {
	const result = await fetchDocument(cwd, options)
	if (!result?.document) throw new Error("WordPress introspection returned no document.")

	const generated = generateWordPressModule(result.document)
	await assertGeneratedClientCompiles(generated)
	return generated.source
}

/**
 * Write `introspection.ts` at its resolved path, revalidating against the ETag cache. The one place
 * the introspection reaches disk, whether or not the project has a server: a server-backed app writes
 * it under `generated/`, and a package that only ships procedures writes it at its own `dir.introspection`.
 */
export async function generateIntrospectionOnce(
	cfg: ResolvedConfig,
	options: GenerateWordPressOptions = {},
): Promise<"generated" | "unchanged"> {
	const file = path.resolve(cfg.cwd, cfg.introspectionPath)
	const metaPath = path.resolve(cfg.cwd, cfg.introspectionMetaPath)
	const result = await fetchDocument(cfg.cwd, options, readWordPressMeta(metaPath, file)?.etag)
	if (!result?.document) return "unchanged"

	// Before the ETag cache, not only before the file: a refused generation that had already
	// stamped the cache would answer its own next poll with a 304 and never retry.
	const generated = generateWordPressModule(result.document)
	await assertGeneratedClientCompiles(generated)

	fs.mkdirSync(path.dirname(file), { recursive: true })
	fs.mkdirSync(path.dirname(metaPath), { recursive: true })
	atomicWrite(file, generated.source)
	atomicWrite(metaPath, wordPressMeta(result.etag, result.document.hash))
	return "generated"
}

/** What a run of {@link generateOnce} did. */
export interface GenerateResult {
	/** The introspection artifact: freshly written, or already current (an unchanged 304). */
	introspection: "generated" | "unchanged"
	/**
	 * The contract:
	 * - `built`: a server was present and its `contract.json` + barrel were written;
	 * - `empty`: a server path was present but its entry exports no `procedures`;
	 * - `none`: no server is configured, so only the introspection was generated.
	 */
	contract: "built" | "empty" | "none"
}

/**
 * Generate everything `dir` resolves: the introspection always, plus the contract and barrel when a
 * server is present. The server is loaded before the introspection is fetched, so a legacy `router`
 * export is named as a migration error even with WordPress unreachable; a server whose entry exports no
 * `procedures` still gets its introspection, and reports `contract: "empty"`.
 */
export async function generateOnce(cfg: ResolvedConfig, options: GenerateWordPressOptions = {}): Promise<GenerateResult> {
	loadEnvFiles(cfg.cwd)

	let procedures: AnyProcedureTree | undefined
	if (cfg.server) {
		const entry = path.resolve(cfg.cwd, cfg.server.entry)
		const server = await importIgnoringVirtualModules<{ procedures?: AnyProcedureTree; router?: unknown }>(cfg.cwd, entry)
		if (!server.procedures && server.router) throw new LegacyRouterExportError(cfg.server.entry)
		procedures = server.procedures
	}

	const introspection = await generateIntrospectionOnce(cfg, options)

	if (!cfg.server) return { introspection, contract: "none" }
	if (!procedures) return { introspection, contract: "empty" }

	const contract = JSON.stringify(await generateContract(procedures))
	fs.mkdirSync(path.resolve(cfg.cwd, cfg.server.contractDir), { recursive: true })
	atomicWrite(path.resolve(cfg.cwd, cfg.server.contractPath), contract)
	atomicWrite(path.resolve(cfg.cwd, cfg.server.barrelPath), CONTRACT_BARREL)

	if (introspection === "generated") log.success("WordPress introspection generated")
	return { introspection, contract: "built" }
}
