name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: pnpm

    - name: Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2

    - shell: bash
      run: pnpm install --frozen-lockfile
