import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import { readManifest } from "../presets/template"
import { getVersion } from "../utils"
import { applyManifestWiring, bootstrapArgs } from "./create"

const here = path.dirname(fileURLToPath(import.meta.url))
const templateDir = path.resolve(here, "../../../../../templates/nextjs")

describe("bootstrapArgs", () => {
	const manifest = readManifest(templateDir)

	it("builds the framework create argv from the manifest, substituting {{pm}}", () => {
		const argv = bootstrapArgs(manifest, "pnpm", "my-app")
		expect(argv?.slice(0, 4)).toEqual(["pnpm", "create", "next-app@latest", "my-app"])
		// The {{pm}} token is resolved to the chosen manager, and no unresolved tokens remain.
		expect(argv).toContain("--use-pnpm")
		expect(argv?.some((arg) => arg.includes("{{pm}}"))).toBe(false)
	})

	it("routes npm flags through a -- separator", () => {
		const argv = bootstrapArgs(manifest, "npm", "my-app")
		expect(argv?.slice(0, 5)).toEqual(["npm", "create", "next-app@latest", "my-app", "--"])
		expect(argv).toContain("--use-npm")
	})
})

/**
 * The wiring half of `create`, given an already-fetched template directory (the framework CLI is not
 * run here). A temp directory is seeded to look like create-next-app's output — a `package.json`, a
 * tsconfig with the `@/*` alias, and a root layout that renders `<html>` and carries a static
 * `metadata` export — then `applyManifestWiring` layers Kizlo on top. Asserts the invariants that make
 * it a wired project.
 */
describe("applyManifestWiring", () => {
	const manifest = readManifest(templateDir)
	let dir: string

	/** Seed `dir` with the files create-next-app would have produced (with the flags the manifest uses). */
	function seedNextApp(): void {
		fs.writeFileSync(path.join(dir, "package.json"), JSON.stringify({ name: "my-app", dependencies: { next: "^16.0.0" } }, null, 2))
		fs.writeFileSync(path.join(dir, "tsconfig.json"), JSON.stringify({ compilerOptions: { paths: { "@/*": ["./src/*"] } } }))
		const layout = `import type { Metadata } from "next"

export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" }

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
`
		fs.mkdirSync(path.join(dir, "src/app"), { recursive: true })
		fs.writeFileSync(path.join(dir, "src/app/layout.tsx"), layout)
	}

	beforeEach(() => {
		dir = fs.mkdtempSync(path.join(os.tmpdir(), "kizlo-create-"))
		seedNextApp()
	})

	afterEach(() => {
		fs.rmSync(dir, { recursive: true, force: true })
	})

	it("scaffolds the wiring and starter files, records the kizlo dep, and patches the layout", async () => {
		await applyManifestWiring(dir, templateDir, manifest, { devPath: "wordpress" })

		// Wiring files land where the manifest tokens place them.
		expect(fs.existsSync(path.join(dir, "src/lib/kizlo/server/index.ts"))).toBe(true)
		expect(fs.existsSync(path.join(dir, "src/app/api/kizlo/[[...rest]]/route.ts"))).toBe(true)
		// Generated contract is seeded so imports resolve before the first watch/generate.
		expect(fs.existsSync(path.join(dir, "src/lib/kizlo/server/generated/contract.json"))).toBe(true)

		// Demo starter files come along on create (they are skipped by init).
		expect(fs.existsSync(path.join(dir, "src/app/page.tsx"))).toBe(true)
		expect(fs.existsSync(path.join(dir, "src/app/blog/[slug]/page.tsx"))).toBe(true)
		expect(fs.existsSync(path.join(dir, "src/app/globals.css"))).toBe(true)

		// kizlo.config.ts is written by create (not copied), with the local dev path.
		const config = fs.readFileSync(path.join(dir, "kizlo.config.ts"), "utf8")
		expect(config).toContain('dir: "src/lib/kizlo"')
		expect(config).toContain('dev: { path: "wordpress" }')

		// The kizlo dependency is recorded (from the template's stamped version) without installing.
		const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"))
		expect(pkg.dependencies.kizlo).toBe(`^${getVersion()}`)
		expect(pkg.dependencies.next).toBe("^16.0.0")

		// The framework's root layout is patched: Kizlo's SEO exports replace the static `metadata`.
		const layout = fs.readFileSync(path.join(dir, "src/app/layout.tsx"), "utf8")
		expect(layout).toContain("generateMetadata")
		expect(layout).toContain("createRootMetadata")
		expect(layout).not.toContain("export const metadata")
	})
})
