name: PR

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: {}

jobs:
  validate-title:
    name: Validate title
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    steps:
      - name: Validate semantic title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            perf
            test
            ci
            build
            style
            revert
          requireScope: false

  preview:
    name: Publish package previews
    if: github.event.action != 'edited'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}-preview-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/gh-actions/setup

      - name: Build packages
        run: pnpm turbo --filter "./packages/*" build

      - name: Publish previews
        run: pnpm exec pkg-pr-new publish --pnpm --previewVersion --peerDeps --packageManager=pnpm --no-template './packages/*'
