name: Release

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/gh-actions/setup

      - name: Check packages for common errors
        run: pnpm turbo --filter "./packages/*" build typecheck

      - name: Create Release
        id: changeset
        uses: changesets/action@v1.5.3
        with:
          version: pnpm run changeset:version
          commit: "chore(release): 📦 version packages"
          title: "chore(release): 📦  version packages"
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
