import { zodResolver } from "@hookform/resolvers/zod"
import { Globe, Plus, Trash } from "@phosphor-icons/react"
import { Controller, useFieldArray, useForm } from "react-hook-form"
import { TextInputField } from "@/modules/settings/shared/fields"
import { SettingsGroup, SettingsSet } from "@/modules/settings/shared/settings"
import { type CrawlingSettingsInput, type CrawlingSettingsOutput, CrawlingSettingsSchema } from "@/shared/lib/schema"
import { useSettings } from "@/shared/lib/settings"
import { Button } from "@/shared/ui/button"
import { Card, CardContent } from "@/shared/ui/card"
import { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldSeparator } from "@/shared/ui/field"
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput } from "@/shared/ui/input-group"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/ui/select"
import { Switch } from "@/shared/ui/switch"

export function CrawlingSettingsPage() {
	const { settings, update, isLoading } = useSettings()

	const form = useForm<CrawlingSettingsInput, unknown, CrawlingSettingsOutput>({
		resolver: zodResolver(CrawlingSettingsSchema),
		defaultValues: {
			sitemaps: {
				pathname_structure: settings?.crawling.sitemaps.pathname_structure ?? "",
			},
			robots: {
				include_sitemap: settings?.crawling.robots.include_sitemap ?? true,
				custom_rules: settings?.crawling.robots.custom_rules ?? [],
			},
		},
	})

	const { fields, append, remove } = useFieldArray({
		control: form.control,
		name: "robots.custom_rules",
	})

	function onSubmit(data: CrawlingSettingsOutput) {
		update("crawling", data)
	}

	return (
		<form onSubmit={form.handleSubmit(onSubmit)} className="relative">
			<SettingsSet isLoading={isLoading}>
				<SettingsGroup
					heading={<>Sitemap</>}
					description={<>Configure your sitemap index URL. Used as the base path for all sitemaps generated by Kizlo.</>}
				>
					<Card>
						<CardContent>
							<FieldGroup>
								<TextInputField
									control={form.control}
									name="sitemaps.pathname_structure"
									label="Sitemap Pathname"
									description="The pathname for your sitemap index. Defaults to /sitemap_index.xml if left blank."
									icon={<Globe />}
									placeholder="/sitemap_index.xml"
								/>
							</FieldGroup>
						</CardContent>
					</Card>
				</SettingsGroup>

				<FieldSeparator />

				<SettingsGroup
					heading={<>Robots</>}
					description={<>Control how search engines crawl your site. These settings are used to generate your robots.txt data.</>}
				>
					<Card>
						<CardContent>
							<FieldGroup>
								<Controller
									name="robots.include_sitemap"
									control={form.control}
									render={({ field, fieldState }) => (
										<Field orientation="horizontal" data-invalid={fieldState.invalid}>
											<FieldContent>
												<FieldLabel htmlFor="robots.include_sitemap">Include Sitemap</FieldLabel>
												<FieldDescription>Automatically append your sitemap URL to the robots.txt output.</FieldDescription>
											</FieldContent>
											<Switch
												id="robots.include_sitemap"
												checked={field.value}
												onCheckedChange={field.onChange}
												aria-invalid={fieldState.invalid}
											/>
											{fieldState.invalid && <FieldError errors={[fieldState.error]} />}
										</Field>
									)}
								/>
							</FieldGroup>
						</CardContent>
					</Card>

					<Card>
						<CardContent>
							<FieldGroup>
								{fields.map((item, index) => (
									<Field key={item.id}>
										<FieldGroup>
											<div className="flex gap-2">
												<Controller
													name={`robots.custom_rules.${index}.user_agent`}
													control={form.control}
													render={({ field, fieldState }) => (
														<Field className="flex-1" data-invalid={fieldState.invalid}>
															<FieldLabel>User Agent</FieldLabel>
															<InputGroup>
																<InputGroupInput {...field} placeholder="*" aria-invalid={fieldState.invalid} />
															</InputGroup>
															{fieldState.invalid && <FieldError errors={[fieldState.error]} />}
														</Field>
													)}
												/>

												<Controller
													name={`robots.custom_rules.${index}.rule`}
													control={form.control}
													render={({ field, fieldState }) => (
														<Field className="w-36" data-invalid={fieldState.invalid}>
															<FieldLabel>Rule</FieldLabel>
															<Select value={field.value} onValueChange={field.onChange}>
																<SelectTrigger aria-invalid={fieldState.invalid}>
																	<SelectValue placeholder="Select" />
																</SelectTrigger>
																<SelectContent>
																	<SelectItem value="allow">Allow</SelectItem>
																	<SelectItem value="disallow">Disallow</SelectItem>
																</SelectContent>
															</Select>
															{fieldState.invalid && <FieldError errors={[fieldState.error]} />}
														</Field>
													)}
												/>

												<Controller
													name={`robots.custom_rules.${index}.path`}
													control={form.control}
													render={({ field, fieldState }) => (
														<Field className="flex-1" data-invalid={fieldState.invalid}>
															<FieldLabel>Path</FieldLabel>
															<InputGroup>
																<InputGroupInput {...field} placeholder="/wp-admin/" aria-invalid={fieldState.invalid} />
																<InputGroupAddon align="inline-end">
																	<InputGroupButton
																		type="button"
																		variant="ghost"
																		size="icon-xs"
																		onClick={() => remove(index)}
																		aria-label="Remove rule"
																	>
																		<Trash />
																	</InputGroupButton>
																</InputGroupAddon>
															</InputGroup>
															{fieldState.invalid && <FieldError errors={[fieldState.error]} />}
														</Field>
													)}
												/>
											</div>
										</FieldGroup>
									</Field>
								))}

								<Button type="button" variant="outline" size="sm" onClick={() => append({ user_agent: "", rule: "disallow", path: "" })}>
									<Plus />
									Add Rule
								</Button>
							</FieldGroup>
						</CardContent>
					</Card>
				</SettingsGroup>
			</SettingsSet>
		</form>
	)
}
