import { zodResolver } from "@hookform/resolvers/zod"
import { PlusIcon, TrashIcon } from "@phosphor-icons/react"
import { Controller, useFieldArray, useForm } from "react-hook-form"
import { SwitchField, TextInputField } from "@/shared/components/fields"
import { SettingsForm, SettingsSection } from "@/shared/components/settings"
import { Button } from "@/shared/components/ui/button"
import { TextInput } from "@/shared/components/ui/input"
import { Select } from "@/shared/components/ui/select"
import { type CrawlingSettingsInput, type CrawlingSettingsOutput, CrawlingSettingsSchema } from "@/shared/lib/schema"
import { useSettings } from "@/shared/lib/settings"

const RULE_OPTIONS = [
	{ label: "Allow", value: "allow" },
	{ label: "Disallow", value: "disallow" },
]

export function CrawlingSettingsPage() {
	const { settings, update, isLoading } = useSettings()

	const form = useForm<CrawlingSettingsInput, unknown, CrawlingSettingsOutput>({
		resolver: zodResolver(CrawlingSettingsSchema),
		defaultValues: {
			sitemaps: {
				pathname_structure: settings?.crawling.sitemaps.pathname_structure ?? "",
			},
			robots: {
				include_sitemap: settings?.crawling.robots.include_sitemap ?? true,
				custom_rules: settings?.crawling.robots.custom_rules ?? [],
			},
		},
	})

	const { fields, append, remove } = useFieldArray({
		control: form.control,
		name: "robots.custom_rules",
	})

	async function onSubmit(data: CrawlingSettingsOutput) {
		await update("crawling", data)
		form.reset(form.getValues())
	}

	return (
		<SettingsForm isLoading={isLoading} isDirty={form.formState.isDirty} onSubmit={form.handleSubmit(onSubmit)}>
			<SettingsSection title="Sitemap" desc="Configure your sitemap index URL. Used as the base path for all sitemaps generated by Kizlo.">
				<TextInputField
					control={form.control}
					name="sitemaps.pathname_structure"
					label="Sitemap Pathname"
					description="The pathname for your sitemap index. Defaults to /sitemap_index.xml if left blank."
					placeholder="/sitemap_index.xml"
				/>
			</SettingsSection>

			<SettingsSection
				title="Robots"
				desc="Control how search engines crawl your site. These settings are used to generate your robots.txt data."
			>
				<SwitchField
					control={form.control}
					name="robots.include_sitemap"
					label="Include Sitemap"
					description="Automatically append your sitemap URL to the robots.txt output."
				/>

				<div className="flex flex-col gap-4">
					{fields.map((item, index) => (
						<div key={item.id} className="flex items-center gap-2">
							<Controller
								name={`robots.custom_rules.${index}.user_agent`}
								control={form.control}
								render={({ field }) => (
									<TextInput
										name={field.name}
										label="User Agent"
										placeholder="*"
										value={field.value ?? ""}
										onChange={field.onChange}
										className="flex-1"
									/>
								)}
							/>

							<Controller
								name={`robots.custom_rules.${index}.rule`}
								control={form.control}
								render={({ field }) => (
									<Select
										name={field.name}
										label="Rule"
										options={RULE_OPTIONS}
										value={field.value ?? ""}
										onChange={field.onChange}
										className="w-36"
									/>
								)}
							/>

							<Controller
								name={`robots.custom_rules.${index}.path`}
								control={form.control}
								render={({ field }) => (
									<TextInput
										name={field.name}
										label="Path"
										placeholder="/wp-admin/"
										value={field.value ?? ""}
										onChange={field.onChange}
										className="flex-1"
									/>
								)}
							/>

							<Button type="button" variant="ghost" size="sm" onClick={() => remove(index)} aria-label="Remove rule" className="mb-0.5">
								<TrashIcon />
							</Button>
						</div>
					))}

					<Button type="button" variant="secondary" size="sm" onClick={() => append({ user_agent: "", rule: "disallow", path: "" })}>
						<PlusIcon />
						Add Rule
					</Button>
				</div>
			</SettingsSection>
		</SettingsForm>
	)
}
