import { zodResolver } from "@hookform/resolvers/zod"
import { GlobeIcon, SearchIcon, TypeIcon } from "lucide-react"
import { Controller, useForm } from "react-hook-form"
import { TextInputField } from "@/modules/settings/shared/fields"
import { MediaPicker } from "@/modules/settings/shared/media-picker"
import { SettingsGroup, SettingsSet } from "@/modules/settings/shared/settings"
import { SiteSettingsSchema, type SiteSettingsSchemaInput, type SiteSettingsSchemaOutput } from "@/shared/lib/schema"
import { useSettings } from "@/shared/lib/settings"
import { Card, CardContent } from "@/shared/ui/card"
import { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldSeparator } from "@/shared/ui/field"
import { RadioGroup, RadioGroupItem } from "@/shared/ui/radio-group"

export function SiteSettingsPage() {
	const { settings, update, isLoading } = useSettings()

	const form = useForm<SiteSettingsSchemaInput, unknown, SiteSettingsSchemaOutput>({
		resolver: zodResolver(SiteSettingsSchema),
		defaultValues: {
			name: settings?.site.name ?? "",
			secret: settings?.site.secret ?? "",
			alternate_name: settings?.site.alternate_name ?? "",
			fallback_image: settings?.site.fallback_image?.id ?? null,
			search_action_structure: settings?.site.search_action_structure ?? "",
			tagline: settings?.site.tagline ?? "",
			title_separator: settings?.site.title_separator,
			url: settings?.site.url ?? "",
		},
	})

	function onSubmit(data: SiteSettingsSchemaOutput) {
		update("site", data)
	}

	return (
		<form onSubmit={form.handleSubmit(onSubmit)} className="relative">
			<SettingsSet isLoading={isLoading}>
				<SettingsGroup
					heading="Site identity"
					description={<>Core settings that identify your site to Kizlo and secure communication between the plugin and Kizlo sdk.</>}
				>
					<Card>
						<CardContent>
							<FieldGroup>
								<TextInputField
									control={form.control}
									name="url"
									label="Site URL"
									icon={<GlobeIcon />}
									description="The canonical URL of your WordPress site. Used as the base for previews, SEO canonical tags, and sitemaps generated by Kizlo."
									placeholder="https://yoursite.com"
								/>

								<TextInputField
									control={form.control}
									name="secret"
									type="password"
									label="Site Secret"
									placeholder="••••••••••••••••"
									description="Shared secret used to sign preview tokens and verify webhook payloads. Keep this private — anyone with this value can issue valid requests on behalf of your site."
								/>
							</FieldGroup>
						</CardContent>
					</Card>
				</SettingsGroup>
				<SettingsGroup
					heading={<>Site info</>}
					description={
						<>
							Configure your website's core details such as name, URL, branding defaults, and search behavior used across metadata and
							structured data.
						</>
					}
				>
					<Card>
						<CardContent>
							<FieldGroup>
								<TextInputField
									name="name"
									label="Site Name"
									icon={<TypeIcon />}
									control={form.control}
									placeholder="Acme Inc."
									description="Your site's primary name. Appears in browser tab titles, Google search results, and Open Graph tags. Defaults to the WordPress site title if left blank."
								/>

								<TextInputField
									label="Alternate Name"
									icon={<TypeIcon />}
									name="alternate_name"
									control={form.control}
									placeholder="Acme"
									description="A shorter or abbreviated name (e.g. an acronym or brand nickname). Added to the <code>alternateName</code> field in your site's Schema.org structured data."
								/>

								<TextInputField
									name="tagline"
									control={form.control}
									placeholder="Building tools people love"
									label="Tagline"
									description='A short phrase describing your site. Used as the homepage meta description fallback and in structured data. Synced from your WordPress "Tagline" setting.'
									icon={<TypeIcon />}
								/>
							</FieldGroup>
						</CardContent>
					</Card>
				</SettingsGroup>

				<FieldSeparator />

				<SettingsGroup
					heading={<>SEO Defaults</>}
					description={
						<>
							Fallback assets used when a post or page has no SEO image set. Shown when your content is shared on X, Facebook, LinkedIn, and
							similar platforms.
						</>
					}
				>
					<Card>
						<CardContent>
							<FieldGroup>
								<Controller
									name="fallback_image"
									control={form.control}
									render={({ field, fieldState }) => (
										<Field data-invalid={fieldState.invalid}>
											<FieldLabel htmlFor="fallback_image">Default Social Image</FieldLabel>
											<MediaPicker
												type="image"
												height={630}
												width={1200}
												url={settings?.site.fallback_image?.url}
												onValueChange={(item) => field.onChange(item?.id ?? null)}
											/>
											<FieldDescription>
												Used as the Open Graph / Twitter Card fallback image when no featured image is available. Recommended size:{" "}
												<strong>1200 × 630 px</strong>.
											</FieldDescription>
											{fieldState.invalid && <FieldError errors={[fieldState.error]} />}
										</Field>
									)}
								/>
							</FieldGroup>
						</CardContent>
					</Card>

					<Card>
						<CardContent>
							<FieldGroup>
								<Controller
									name="title_separator"
									control={form.control}
									render={({ field, fieldState }) => (
										<Field data-invalid={fieldState.invalid}>
											<FieldLabel htmlFor="title_separator">Title Separator</FieldLabel>

											<RadioGroup value={field.value} onValueChange={field.onChange} className="flex flex-wrap">
												{settings?.constants.site.title_separators.map((item) => (
													<FieldLabel key={item} htmlFor={item} className="size-14!">
														<Field className="flex items-center justify-center text-center">
															<FieldContent>{item}</FieldContent>
															<RadioGroupItem value={item} id={item} className="hidden" />
														</Field>
													</FieldLabel>
												))}
											</RadioGroup>

											<FieldDescription>
												The character placed between the page name and the site name in the HTML <code>&lt;title&gt;</code> tag. Common
												choices: <code>|</code>, <code>–</code>, <code>·</code>, <code>»</code>.
											</FieldDescription>
											{fieldState.invalid && <FieldError errors={[fieldState.error]} />}
										</Field>
									)}
								/>
							</FieldGroup>
						</CardContent>
					</Card>

					<Card>
						<CardContent>
							<TextInputField
								name="search_action_structure"
								control={form.control}
								label="Search Results URL Template"
								icon={<SearchIcon />}
								description={
									<>
										Use <code>{"{{search_term_string}}"}</code> as user's query placeholder — for example{" "}
										<code>https://yoursite.com/?s={"{{search_term_string}}"}</code>.
									</>
								}
							/>
						</CardContent>
					</Card>
				</SettingsGroup>
			</SettingsSet>
		</form>
	)
}
