import { zodResolver } from "@hookform/resolvers/zod"
import { Controller, useForm } from "react-hook-form"
import { FieldError, SwitchField, TextInputField } from "@/shared/components/fields"
import { SettingsForm, SettingsSection } from "@/shared/components/settings"
import { MediaPicker } from "@/shared/components/ui/media-picker"
import { SiteSettingsSchema, type SiteSettingsSchemaInput, type SiteSettingsSchemaOutput } from "@/shared/lib/schema"
import { useSettings } from "@/shared/lib/settings"
import { cn } from "@/shared/lib/utils"

export function SiteSettingsPage() {
	const { settings, update, isLoading } = useSettings()

	const form = useForm<SiteSettingsSchemaInput, unknown, SiteSettingsSchemaOutput>({
		resolver: zodResolver(SiteSettingsSchema),
		defaultValues: {
			name: settings?.site.name ?? "",
			secret: settings?.site.secret ?? "",
			alternate_name: settings?.site.alternate_name ?? "",
			fallback_image: settings?.site.fallback_image?.id ?? null,
			search_action_structure: settings?.site.search_action_structure ?? "",
			tagline: settings?.site.tagline ?? "",
			title_separator: settings?.site.title_separator,
			url: settings?.site.url ?? "",
			backend_url: settings?.site.backend_url ?? "",
			discourage_search_engines: settings?.site.discourage_search_engines ?? false,
		},
	})

	async function onSubmit(data: SiteSettingsSchemaOutput) {
		await update("site", data)
		form.reset(form.getValues())
	}

	return (
		<SettingsForm
			isLoading={isLoading}
			isDirty={form.formState.isDirty}
			onSubmit={form.handleSubmit(onSubmit)}
			onCancel={() => form.reset()}
		>
			<SettingsSection
				title="Site identity"
				desc="Core settings that identify your site to Kizlo and secure communication between the plugin and Kizlo sdk."
			>
				<TextInputField
					control={form.control}
					name="url"
					label="Site URL"
					description="The canonical URL of your WordPress site. Used as the base for previews, SEO canonical tags, and sitemaps generated by Kizlo."
					placeholder="https://yoursite.com"
				/>

				<TextInputField
					control={form.control}
					name="backend_url"
					label="Backend URL"
					description="The base URL where your Kizlo backend is mounted. Events are delivered here automatically — the webhook path is appended for you (e.g. https://example.com/api/kizlo/webhooks)."
					placeholder="https://example.com/api/kizlo"
				/>

				<TextInputField
					control={form.control}
					name="secret"
					type="password"
					label="Site Secret"
					placeholder="••••••••••••••••"
					description="Shared secret used to sign preview tokens and verify webhook payloads. Keep this private — anyone with this value can issue valid requests on behalf of your site."
				/>
			</SettingsSection>

			<SettingsSection
				title="Site info"
				desc="Configure your website's core details such as name, URL, branding defaults, and search behavior used across metadata and structured data."
			>
				<TextInputField
					name="name"
					label="Site Name"
					control={form.control}
					placeholder="Acme Inc."
					description="Your site's primary name. Appears in browser tab titles, Google search results, and Open Graph tags. Defaults to the WordPress site title if left blank."
				/>

				<TextInputField
					label="Alternate Name"
					name="alternate_name"
					control={form.control}
					placeholder="Acme"
					description="A shorter or abbreviated name (e.g. an acronym or brand nickname). Added to the alternateName field in your site's Schema.org structured data."
				/>

				<TextInputField
					name="tagline"
					control={form.control}
					placeholder="Building tools people love"
					label="Tagline"
					description='A short phrase describing your site. Used as the homepage meta description fallback and in structured data. Synced from your WordPress "Tagline" setting.'
				/>
			</SettingsSection>

			<SettingsSection
				title="SEO Defaults"
				desc="Fallback assets used when a post or page has no SEO image set. Shown when your content is shared on X, Facebook, LinkedIn, and similar platforms."
			>
				<Controller
					name="fallback_image"
					control={form.control}
					render={({ field, fieldState }) => (
						<div>
							<MediaPicker
								type="image"
								label="Default Social Image"
								desc={
									<>
										Used as the Open Graph / Twitter Card fallback image when no featured image is available. Recommended size:{" "}
										<strong>1200 × 630 px</strong>.
									</>
								}
								url={settings?.site.fallback_image?.src}
								value={typeof field.value === "number" ? field.value : null}
								onValueChange={(item) => field.onChange(item?.id ?? null)}
							/>
							<FieldError message={fieldState.error?.message} />
						</div>
					)}
				/>

				<Controller
					name="title_separator"
					control={form.control}
					render={({ field, fieldState }) => (
						<div className="flex flex-col gap-3">
							<span className="font-medium text-neutral-900 text-sm">Title Separator</span>

							<div className="flex flex-wrap gap-2">
								{settings?.constants.site.title_separators.map((item) => {
									const selected = field.value === item

									return (
										<label
											key={item}
											className={cn(
												"flex size-12 cursor-pointer items-center justify-center rounded-lg border text-lg transition-colors",
												selected ? "wp-ring border-primary" : "border-neutral-300 hover:border-primary",
											)}
										>
											<input
												type="radio"
												name="title_separator"
												value={item}
												checked={selected}
												onChange={() => field.onChange(item)}
												className="sr-only"
											/>
											{item}
										</label>
									)
								})}
							</div>

							<p className="my-0 text-neutral-500 text-sm leading-relaxed">
								The character placed between the page name and the site name in the HTML title tag. Common choices: | – · ».
							</p>

							<FieldError message={fieldState.error?.message} />
						</div>
					)}
				/>

				<TextInputField
					name="search_action_structure"
					control={form.control}
					label="Search Results URL Template"
					description="Use {{search_term_string}} as the user's query placeholder — for example https://yoursite.com/?s={{search_term_string}}."
				/>
			</SettingsSection>

			<SettingsSection title="Search engine visibility" desc="Controls whether search engines are allowed to index your headless frontend.">
				<SwitchField
					name="discourage_search_engines"
					control={form.control}
					label="Discourage search engines from indexing this site"
					description="When on, robots.txt blocks all crawlers and every page emits a noindex tag. This applies to your Kizlo frontend and is independent of WordPress's own setting. Leave off unless you want the frontend hidden from search."
				/>
			</SettingsSection>
		</SettingsForm>
	)
}
